// SPDX-License-Identifier: MPL-2.0
//! The executable rule catalogue. Every built-in rule has a falsifier corpus.
pub mod assets;
pub mod budget;
pub mod documents;
pub mod repository;
mod syntax;
use pons_core::{EvidenceClass, Lang, Rule, RuleMeta, Severity};
pub use syntax::SyntaxRule;

pub fn registry() -> Vec<Box<dyn Rule>> {
    (0..8)
        .map(|i| Box::new(SyntaxRule(i)) as Box<dyn Rule>)
        .collect()
}
pub fn metadata() -> Vec<RuleMeta> {
    registry()
        .iter()
        .map(|r| r.meta())
        .chain(repository::metadata())
        .chain(documents::metadata())
        .chain(assets::metadata())
        .chain([budget::metadata()])
        .collect()
}
pub fn meta(id: &str, message: &str, counter: &str, languages: Vec<String>) -> RuleMeta {
    RuleMeta {
        id: id.into(),
        evidence: EvidenceClass::Heuristic,
        severity: Severity::Warn,
        languages,
        message: message.into(),
        counter_condition: counter.into(),
    }
}
pub fn source_languages() -> Vec<String> {
    Lang::ALL.iter().map(|l| l.name().into()).collect()
}
/// Repository review messages carry their concrete observation in ordinary
/// output; users should not need --explain to discover the missing filename.
pub(crate) fn review(
    meta: &RuleMeta,
    location: pons_core::Location,
    observation: impl Into<String>,
) -> pons_core::Finding {
    let observation = observation.into();
    let mut finding = pons_core::Finding::new(meta, location, &observation);
    finding.message = observation;
    finding
}
pub fn catalogue() -> String {
    let mut text = "// SPDX-License-Identifier: CC-BY-SA-4.0\n= Pons rule catalogue\n\nGenerated by `pons catalogue`; change the registry, then regenerate.\n\nRules state their evidence and counter-condition below. PROTOCOL resource arithmetic is conditional on an explicit contract and a completed literal loop. Full CFG/dataflow and inferred source typestate remain unimplemented.\n\n".to_string();
    for m in metadata() {
        text.push_str(&format!("== {}\n\n* {}\n* Evidence: `{:?}` / `{:?}`; severity: `{:?}`\n* Languages: {}\n* Counter-condition: {}\n\n",m.id,m.message,m.evidence.tier(),m.evidence,m.severity,m.languages.join(", "),m.counter_condition));
    }
    text.trim_end().to_owned() + "\n"
}
