# SPDX-License-Identifier: MPL-2.0
[package]
name = "pons-cli"
description = "Pons: rookie mistakes beyond a successful compilation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "pons"
path = "../../src/main.rs"

[dependencies]
pons-core = { path = "../pons-core" }
pons-rules = { path = "../pons-rules" }
pons-protocols = { path = "../pons-protocols" }
anyhow.workspace = true
clap.workspace = true
clap_mangen.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
